panel/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tweetlist.urls')),
]

tweetlist/urls.py
from django.conf.urls import url
from . import views
app_name = 'tweetlist'


urlpatterns = [
    url(r'^$', views.home , name='home'),
    url(r'^listweets$', views.listweets, name='listweets'),
]

tweetlist/models.py
from django.db import models

# Create your models here.

tweetlist/forms.py
#from django import forms

#class Tweets(forms.Form):
 #   twittername = forms.CharField(max_length = None)

tweetlist/views.py
from django.shortcuts import render,redirect,get_object_or_404
#from .forms import Tweets
import requests
import requests_oauthlib
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect



authenticate = requests_oauthlib.OAuth1(API_kEY,API_SECRET,ACCESS_TOKEN,ACCESS_TOKEN_SECRET)
url = "https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name="

def home(request):
    return render(request,'tweetlist/index.html',{})


def listweets(request):
    profileName = str(request.POST.get('profilename',None))
    count = str(request.POST.get('tweetcount',None))
    if count == "":
        count = 7
    else:
        count = str(request.POST.get('tweetcount', None))
    print('------------------------>>>>> -------debug bar <---')
    print(count)
    r = requests.get(url + profileName + "&count="+str(count), auth=authenticate)
    tweets = []
    for tweet in r.json():
        tweets.append(tweet['text'])
    print(tweets)
    return JsonResponse({'profileName': profileName, 'tweets': tweets})

tweetlist/templates/tweetlist/base.html
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: rgba(255, 145, 0, 0.973);
            color: white;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="jumbotron">
        <h1> lisTweets </h1>
        <p> lisTweets is a simple site to list the Tweets of a twitter user </p>
    </div>

    <div class="container">
         {% block content %} 
         
         
         
         
         {% endblock %}

        
    </div>
    
</body>
<footer>
    <div class="footer">

        <center>
            © &nbsp; Powered by Django &hearts;
        </center>
    </div>
</footer>

</html>

tweetlist/templates/tweetlist/index.html
{% extends 'tweetlist/base.html' %} 
{% block content %}


<div class="panel panel-primary">
    <div class="panel-heading">Get Latest Tweets </div>
    <div class="panel-body">
        <form method="POST" id="tweet-form">
        {% csrf_token %}
        <input type="text" name='profilename' id='profilename'  class="form-control" placeholder="Profile Name">
        <br>
        <input type="number" name='tweetcount' id='tweetcount' class="form-control" min="1" max = "10" placeholder="7">
        <br>
        <button type = "submit" class="btn btn-info"  >Get Tweets</a>
        </form>
        </div>
        </div>
        <div class = "response" id = "response">
        Tweets go by this way
        </div>
    <script>
           $(document).ready(function () {
                console.log("ready!");
                $("#tweet-form").submit(function (event) {
                    $.ajax({
                        type: "POST",
                        url: '{% url 'tweetlist:listweets' %}',
                        data: $('#tweet-form').serialize(),
                        success: function (dataa) {
                            console.log(dataa);
                    var storestring = " "
                            for (tweet in dataa.tweets) {
                                 storestring = storestring + "<div class='alert alert-info'>" +
                                 dataa.tweets[tweet] + " </div>" 
                            }
                            storestring = storestring + " " 
                            $('#response').html(storestring);
                        },
                        dataType: 'json'
                    });
                    event.preventDefault();
                });
            });
    </script>
  

{% endblock %}
    

tweetlist/templates/tweetlist/tweetsite.html
{% extends 'tweetlist/base.html' %} {% block content %}

{% for every in tweets %}

<div class="alert alert-info">
     {{ every }}
</div>




{% endfor %}

{% endblock %}